unit UnTest;

interface

uses Windows, SysUtils, Classes, Graphics, Forms, Controls, StdCtrls,
  Buttons, ExtCtrls, ComCtrls, Tabnotbk,  Main, Spin, CheckLst;
Type
  TTest = class(TForm)
    OKBtn: TButton;
    Timer1: TTimer;
    Panel1: TPanel;
    Button2: TButton;
    Button3: TButton;
    StaticText26: TStaticText;
    Button4: TButton;
    Panel3: TPanel;
    Label1: TLabel;
    BitBtn2: TBitBtn;
    Panel4: TPanel;
    Label2: TLabel;
    BitBtn3: TBitBtn;
    GroupBox1: TGroupBox;
    Shape001: TShape;
    Shape002: TShape;
    Shape003: TShape;
    Shape004: TShape;
    StaticText3: TStaticText;
    StaticText4: TStaticText;
    StaticText5: TStaticText;
    StaticText6: TStaticText;
    Edit1: TEdit;
    StaticText7: TStaticText;
    Edit2: TEdit;
    StaticText8: TStaticText;
    StaticText9: TStaticText;
    Edit3: TEdit;
    GroupBox3: TGroupBox;
    Shape005: TShape;
    Shape006: TShape;
    Shape007: TShape;
    StaticText10: TStaticText;
    StaticText11: TStaticText;
    StaticText12: TStaticText;
    StaticText13: TStaticText;
    Edit4: TEdit;
    Shape008: TShape;
    Shape009: TShape;
    Shape010: TShape;
    Shape011: TShape;
    Shape012: TShape;
    Shape013: TShape;
    StaticText17: TStaticText;
    StaticText18: TStaticText;
    StaticText27: TStaticText;
    StaticText28: TStaticText;
    StaticText29: TStaticText;
    StaticText30: TStaticText;
    Shape014: TShape;
    Shape015: TShape;
    StaticText31: TStaticText;
    StaticText32: TStaticText;
    Bevel1: TBevel;
    StaticText33: TStaticText;
    Edit5: TEdit;
    StaticText14: TStaticText;
    Edit6: TEdit;
    StaticText15: TStaticText;
    Edit7: TEdit;
    StaticText16: TStaticText;
    Edit8: TEdit;
    StaticText34: TStaticText;
    Edit9: TEdit;
    StaticText35: TStaticText;
    Edit10: TEdit;
    StaticText36: TStaticText;
    Shape016: TShape;
    StaticText37: TStaticText;
    Shape017: TShape;
    StaticText38: TStaticText;
    Shape018: TShape;
    StaticText39: TStaticText;
    GroupBox4: TGroupBox;
    Shape022: TShape;
    Shape023: TShape;
    Shape026: TShape;
    StaticText43: TStaticText;
    StaticText44: TStaticText;
    StaticText51: TStaticText;
    Edit14: TEdit;
    StaticText55: TStaticText;
    Edit15: TEdit;
    StaticText56: TStaticText;
    Edit16: TEdit;
    StaticText57: TStaticText;
    Edit17: TEdit;
    StaticText58: TStaticText;
    Edit18: TEdit;
    StaticText47: TStaticText;
    Edit19: TEdit;
    StaticText48: TStaticText;
    Edit20: TEdit;
    StaticText50: TStaticText;
    Edit21: TEdit;
    StaticText52: TStaticText;
    GroupBox5: TGroupBox;
    Shape027: TShape;
    StaticText63: TStaticText;
    Edit23: TEdit;
    StaticText64: TStaticText;
    GroupBox6: TGroupBox;
    Shape028: TShape;
    StaticText60: TStaticText;
    Edit24: TEdit;
    StaticText61: TStaticText;
    GroupBox7: TGroupBox;
    Shape030: TShape;
    StaticText62: TStaticText;
    Shape029: TShape;
    StaticText65: TStaticText;
    Shape032: TShape;
    StaticText66: TStaticText;
    Shape031: TShape;
    StaticText67: TStaticText;
    Shape034: TShape;
    StaticText68: TStaticText;
    Shape033: TShape;
    StaticText69: TStaticText;
    GroupBox8: TGroupBox;
    Shape035: TShape;
    Shape036: TShape;
    Shape037: TShape;
    Shape038: TShape;
    StaticText70: TStaticText;
    StaticText71: TStaticText;
    StaticText72: TStaticText;
    StaticText73: TStaticText;
    Edit25: TEdit;
    StaticText74: TStaticText;
    GroupBox9: TGroupBox;
    Shape042: TShape;
    Shape041: TShape;
    Shape046: TShape;
    Shape045: TShape;
    Shape049: TShape;
    Shape048: TShape;
    StaticText75: TStaticText;
    StaticText76: TStaticText;
    StaticText77: TStaticText;
    StaticText78: TStaticText;
    StaticText79: TStaticText;
    StaticText80: TStaticText;
    Shape040: TShape;
    Shape039: TShape;
    Shape044: TShape;
    Shape043: TShape;
    StaticText81: TStaticText;
    StaticText82: TStaticText;
    StaticText83: TStaticText;
    StaticText84: TStaticText;
    StaticText85: TStaticText;
    Shape047: TShape;
    Edit26: TEdit;
    Shape056: TShape;
    StaticText94: TStaticText;
    GroupBox10: TGroupBox;
    Shape057: TShape;
    Shape058: TShape;
    Shape059: TShape;
    Shape060: TShape;
    StaticText95: TStaticText;
    StaticText96: TStaticText;
    StaticText97: TStaticText;
    StaticText98: TStaticText;
    Shape061: TShape;
    StaticText99: TStaticText;
    GroupBox11: TGroupBox;
    Shape062: TShape;
    Shape063: TShape;
    StaticText101: TStaticText;
    StaticText102: TStaticText;
    Edit27: TEdit;
    StaticText104: TStaticText;
    StaticText103: TStaticText;
    Shape064: TShape;
    Label002: TLabel;
    GroupBox12: TGroupBox;
    Shape054: TShape;
    Shape055: TShape;
    StaticText86: TStaticText;
    StaticText2: TStaticText;
    GroupBox13: TGroupBox;
    StaticText87: TStaticText;
    StaticText105: TStaticText;
    Shape050: TShape;
    Shape051: TShape;
    GroupBox14: TGroupBox;
    Shape052: TShape;
    Shape053: TShape;
    StaticText89: TStaticText;
    StaticText91: TStaticText;
    GroupBox017: TGroupBox;
    CheckBox010: TCheckBox;
    CheckBox011: TCheckBox;
    CheckBox012: TCheckBox;
    CheckBox1: TCheckBox;
    CheckBox2: TCheckBox;
    CheckBox3: TCheckBox;
    Label4: TLabel;
    Edit022: TEdit;
    UpDown1: TUpDown;
    Edit28: TEdit;
    UpDown2: TUpDown;
    Edit29: TEdit;
    UpDown3: TUpDown;
    Bevel2: TBevel;
    Label5: TLabel;
    Edit30: TEdit;
    UpDown4: TUpDown;
    Edit31: TEdit;
    UpDown5: TUpDown;
    Edit32: TEdit;
    UpDown6: TUpDown;
    Bevel3: TBevel;
    Edit33: TEdit;
    UpDown7: TUpDown;
    GroupBox15: TGroupBox;
    CheckBox4: TCheckBox;
    CheckBox5: TCheckBox;
    CheckBox6: TCheckBox;
    CheckBox7: TCheckBox;
    CheckBox8: TCheckBox;
    GroupBox018: TGroupBox;
    CheckBox005: TCheckBox;
    GroupBox016: TGroupBox;
    CheckBox001: TCheckBox;
    CheckBox002: TCheckBox;
    CheckBox003: TCheckBox;
    CheckBox004: TCheckBox;
    CheckBox006: TCheckBox;
    CheckBox007: TCheckBox;
    CheckBox008: TCheckBox;
    CheckBox009: TCheckBox;
    GroupBox16: TGroupBox;
    CheckBox025: TCheckBox;
    GroupBox022: TGroupBox;
    CheckBox021: TCheckBox;
    GroupBox17: TGroupBox;
    Edit34: TEdit;
    UpDown8: TUpDown;
    GroupBox024: TGroupBox;
    Edit021: TEdit;
    Button5: TButton;
    StaticText074: TStaticText;
    UpDown9: TUpDown;
    GroupBox18: TGroupBox;
    RadioButton1: TRadioButton;
    RadioButton2: TRadioButton;
    CheckBox9: TCheckBox;
    GroupBox19: TGroupBox;
    Edit35: TEdit;
    UpDown10: TUpDown;
    CheckBox10: TCheckBox;
    GroupBox114: TGroupBox;
    Shape141: TShape;
    Shape148: TShape;
    Shape139: TShape;
    Shape144: TShape;
    Shape143: TShape;
    Shape142: TShape;
    Shape145: TShape;
    Shape146: TShape;
    Shape140: TShape;
    Shape147: TShape;
    StaticText165: TStaticText;
    StaticText172: TStaticText;
    StaticText163: TStaticText;
    StaticText168: TStaticText;
    StaticText167: TStaticText;
    StaticText169: TStaticText;
    StaticText170: TStaticText;
    StaticText164: TStaticText;
    StaticText171: TStaticText;
    StaticText88: TStaticText;
    StaticText90: TStaticText;
    Shape103: TShape;
    GroupBox105: TGroupBox;
    Shape116: TShape;
    Shape117: TShape;
    Shape118: TShape;
    Shape119: TShape;
    StaticText129: TStaticText;
    StaticText130: TStaticText;
    StaticText131: TStaticText;
    StaticText132: TStaticText;
    GroupBox101: TGroupBox;
    Shape105: TShape;
    Shape106: TShape;
    Shape107: TShape;
    Shape102: TShape;
    Shape101: TShape;
    Edit106: TEdit;
    Edit105: TEdit;
    StaticText107: TStaticText;
    StaticText108: TStaticText;
    StaticText111: TStaticText;
    StaticText112: TStaticText;
    StaticText113: TStaticText;
    StaticText109: TStaticText;
    StaticText110: TStaticText;
    Edit125: TEdit;
    StaticText114: TStaticText;
    StaticText92: TStaticText;
    Edit101: TEdit;
    GroupBox112: TGroupBox;
    Shape129: TShape;
    Shape130: TShape;
    Shape131: TShape;
    Shape132: TShape;
    StaticText154: TStaticText;
    StaticText153: TStaticText;
    StaticText156: TStaticText;
    Edit123: TEdit;
    StaticText151: TStaticText;
    Edit124: TEdit;
    StaticText152: TStaticText;
    StaticText157: TStaticText;
    GroupBox108: TGroupBox;
    Shape122: TShape;
    Shape123: TShape;
    StaticText140: TStaticText;
    StaticText141: TStaticText;
    GroupBox110: TGroupBox;
    Shape127: TShape;
    StaticText149: TStaticText;
    GroupBox20: TGroupBox;
    Shape104: TShape;
    StaticText93: TStaticText;
    Shape108: TShape;
    StaticText100: TStaticText;
    Label102: TLabel;
    GroupBox116: TGroupBox;
    CheckBox108: TCheckBox;
    CheckBox109: TCheckBox;
    CheckBox110: TCheckBox;
    CheckBox111: TCheckBox;
    GroupBox21: TGroupBox;
    Edit102: TEdit;
    StaticText106: TStaticText;
    Panel5: TPanel;
    Label200: TLabel;
    GroupBox200: TGroupBox;
    Shape200: TShape;
    Shape201: TShape;
    Shape202: TShape;
    Shape203: TShape;
    Shape204: TShape;
    Shape205: TShape;
    Shape207: TShape;
    Shape206: TShape;
    Shape208: TShape;
    Shape209: TShape;
    StaticText200: TStaticText;
    StaticText201: TStaticText;
    StaticText202: TStaticText;
    StaticText203: TStaticText;
    StaticText204: TStaticText;
    StaticText205: TStaticText;
    StaticText206: TStaticText;
    StaticText208: TStaticText;
    StaticText209: TStaticText;
    StaticText207: TStaticText;
    GroupBox201: TGroupBox;
    Shape210: TShape;
    Shape211: TShape;
    Shape212: TShape;
    Shape213: TShape;
    Shape214: TShape;
    Shape215: TShape;
    Shape216: TShape;
    Shape217: TShape;
    Shape218: TShape;
    Shape219: TShape;
    Shape243: TShape;
    Shape244: TShape;
    StaticText210: TStaticText;
    StaticText212: TStaticText;
    StaticText211: TStaticText;
    StaticText213: TStaticText;
    StaticText214: TStaticText;
    StaticText215: TStaticText;
    StaticText216: TStaticText;
    StaticText217: TStaticText;
    StaticText218: TStaticText;
    StaticText219: TStaticText;
    StaticText243: TStaticText;
    StaticText244: TStaticText;
    GroupBox202: TGroupBox;
    Shape220: TShape;
    Shape221: TShape;
    Shape222: TShape;
    Shape223: TShape;
    Shape224: TShape;
    Shape225: TShape;
    Shape226: TShape;
    Shape227: TShape;
    Shape228: TShape;
    Shape229: TShape;
    Shape230: TShape;
    Shape231: TShape;
    Shape232: TShape;
    Shape242: TShape;
    StaticText220: TStaticText;
    StaticText222: TStaticText;
    StaticText221: TStaticText;
    StaticText223: TStaticText;
    StaticText224: TStaticText;
    StaticText225: TStaticText;
    StaticText226: TStaticText;
    StaticText227: TStaticText;
    StaticText228: TStaticText;
    StaticText229: TStaticText;
    StaticText230: TStaticText;
    StaticText231: TStaticText;
    StaticText232: TStaticText;
    StaticText242: TStaticText;
    GroupBox203: TGroupBox;
    Shape233: TShape;
    Shape234: TShape;
    Shape235: TShape;
    Shape236: TShape;
    Shape237: TShape;
    Shape238: TShape;
    Shape239: TShape;
    Shape240: TShape;
    Shape241: TShape;
    Shape257: TShape;
    StaticText233: TStaticText;
    StaticText235: TStaticText;
    StaticText234: TStaticText;
    StaticText236: TStaticText;
    StaticText237: TStaticText;
    StaticText238: TStaticText;
    StaticText239: TStaticText;
    StaticText240: TStaticText;
    StaticText241: TStaticText;
    StaticText262: TStaticText;
    GroupBox204: TGroupBox;
    Shape245: TShape;
    Shape246: TShape;
    Shape247: TShape;
    Shape248: TShape;
    Shape249: TShape;
    Shape250: TShape;
    Shape252: TShape;
    Shape251: TShape;
    StaticText245: TStaticText;
    StaticText246: TStaticText;
    StaticText247: TStaticText;
    StaticText248: TStaticText;
    StaticText249: TStaticText;
    StaticText250: TStaticText;
    StaticText251: TStaticText;
    StaticText252: TStaticText;
    GroupBox205: TGroupBox;
    Shape253: TShape;
    Shape254: TShape;
    Shape255: TShape;
    Shape256: TShape;
    StaticText253: TStaticText;
    StaticText254: TStaticText;
    StaticText255: TStaticText;
    StaticText256: TStaticText;
    GroupBox206: TGroupBox;
    StaticText257: TStaticText;
    Edit200: TEdit;
    StaticText258: TStaticText;
    Edit201: TEdit;
    StaticText259: TStaticText;
    Edit202: TEdit;
    StaticText260: TStaticText;
    Edit203: TEdit;
    StaticText261: TStaticText;
    Edit204: TEdit;
    GroupBox208: TGroupBox;
    CheckBox200: TCheckBox;
    CheckBox201: TCheckBox;
    CheckBox202: TCheckBox;
    CheckBox203: TCheckBox;
    CheckBox204: TCheckBox;
    CheckBox205: TCheckBox;
    Label3: TLabel;
    BitBtn4: TBitBtn;
    GroupBox207: TGroupBox;
    StaticText263: TStaticText;
    Edit205: TEdit;
    StaticText264: TStaticText;
    Edit206: TEdit;
    StaticText265: TStaticText;
    Edit207: TEdit;
    StaticText266: TStaticText;
    Edit208: TEdit;
    StaticText267: TStaticText;
    Edit209: TEdit;
    StaticText268: TStaticText;
    Edit210: TEdit;
    Edit211: TEdit;
    StaticText269: TStaticText;
    UpDown205: TUpDown;
    UpDown206: TUpDown;
    UpDown207: TUpDown;
    UpDown208: TUpDown;
    UpDown209: TUpDown;
    UpDown210: TUpDown;
    UpDown211: TUpDown;
    procedure FormKeyDown(Sender: TObject; var Key: Word;
      Shift: TShiftState);
    procedure Timer1Timer(Sender: TObject);
    procedure FormCreate(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure _Pointer;
    procedure Button3Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
    procedure Button4Click(Sender: TObject);
    procedure BitBtn2Click(Sender: TObject);
    procedure BitBtn4Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Test: TTest;
  enable_Chief: boolean;
  enable_Pointer: boolean;
  enable_Commander: boolean;
  enable_Driver: boolean;
  analog : array[1..5] of word;

implementation
uses UnOther, UnLVS;

{$R *.DFM}

procedure TTest.FormKeyDown(Sender: TObject; var Key: Word;
  Shift: TShiftState);
var s: string;
begin
  case key of
    VK_ESCAPE:Close;
//    VK_F1: Num_BMP:=1;
//    VK_F2: Num_BMP:=2;
//    VK_F3: Num_BMP:=3;
  end;
//  s:=inttostr(Num_BMP);
//  Label6.Caption:='Экипаж  '+s;
end;

procedure TTest.FormCreate(Sender: TObject);
begin
  Panel1.BringToFront;
  Timer1.Enabled:=true;
  Num_BMP:=2;
//  Label6.Caption:='Экипаж  '+inttostr(Num_BMP);
end;

procedure TTest._Pointer;
begin
 //ЛС0 ----------------------------------------------------------------------
    if Org_Upr_Rm[Num_BMP].nav_imp[0] and $01 = $00 then Shape001.Brush.Color:=clLime
                                                    else Shape001.Brush.Color:=clRed;
    if Org_Upr_Rm[Num_BMP].nav_imp[0] and $02 = $00 then Shape002.Brush.Color:=clLime
                                                    else Shape002.Brush.Color:=clRed;
    if Org_Upr_Rm[Num_BMP].nav_imp[0] and $04 = $00 then Shape003.Brush.Color:=clLime
                                                    else Shape003.Brush.Color:=clRed;
    if Org_Upr_Rm[Num_BMP].nav_imp[0] and $08 = $00 then Shape004.Brush.Color:=clLime
                                                    else Shape004.Brush.Color:=clRed;
 //ЛС0-1 --------------------------------------------------------------------
    edit3.Text:=inttostr(Org_Upr_Rm[Num_BMP].nav_imp[2] shl 8 +Org_Upr_Rm[Num_BMP].nav_imp[1]);
 //ЛС2 ----------------------------------------------------------------------
    edit1.Text:=inttostr(Org_Upr_Rm[Num_BMP].nav_imp[3]);
end;

procedure TTest.Timer1Timer(Sender: TObject);
var a: word;
begin
  if enable_Pointer then begin
    _Pointer;
  end;
end;

procedure TTest.FormClose(Sender: TObject; var Action: TCloseAction);
begin
  Timer1.Enabled:=false;
end;

procedure TTest.Button2Click(Sender: TObject);
begin
  enable_Pointer:=true;
  Timer1.Enabled:=true;
  Panel3.BringToFront;
end;

procedure TTest.Button3Click(Sender: TObject);
begin
  enable_Commander:=true;
  Timer1.Enabled:=true;
  Panel4.BringToFront;
end;


procedure TTest.Button4Click(Sender: TObject);
begin
  enable_Driver:=true;
  Timer1.Enabled:=true;
  Panel5.BringToFront;
end;

procedure TTest.BitBtn2Click(Sender: TObject);
begin
  enable_Chief:=false;
  enable_Pointer:=false;
  enable_Commander:=false;
  Panel1.BringToFront;
end;

procedure TTest.BitBtn4Click(Sender: TObject);
begin
  enable_Chief:=false;
  enable_Pointer:=false;
  enable_Commander:=false;
  Panel1.BringToFront;
end;

end.



